// constants.js

export const COUNTRY_CODES = [
    { code: "+93", country: "AF", label: "🇦🇫 Afghanistan (+93)" },
    { code: "+355", country: "AL", label: "🇦🇱 Albania (+355)" },
    { code: "+213", country: "DZ", label: "🇩🇿 Algeria (+213)" },
    { code: "+1", country: "AS", label: "🇦🇸 American Samoa (+1)" },
    { code: "+376", country: "AD", label: "🇦🇩 Andorra (+376)" },
    { code: "+244", country: "AO", label: "🇦🇴 Angola (+244)" },
    { code: "+1", country: "AI", label: "🇦🇮 Anguilla (+1)" },
    { code: "+1", country: "AG", label: "🇦🇬 Antigua & Barbuda (+1)" },
    { code: "+54", country: "AR", label: "🇦🇷 Argentina (+54)" },
    { code: "+374", country: "AM", label: "🇦🇲 Armenia (+374)" },
    { code: "+61", country: "AU", label: "🇦🇺 Australia (+61)" },
    { code: "+43", country: "AT", label: "🇦🇹 Austria (+43)" },
    { code: "+994", country: "AZ", label: "🇦🇿 Azerbaijan (+994)" },
    { code: "+973", country: "BH", label: "🇧🇭 Bahrain (+973)" },
    { code: "+880", country: "BD", label: "🇧🇩 Bangladesh (+880)" },
    { code: "+32", country: "BE", label: "🇧🇪 Belgium (+32)" },
    { code: "+55", country: "BR", label: "🇧🇷 Brazil (+55)" },
    { code: "+1", country: "CA", label: "🇨🇦 Canada (+1)" },
    { code: "+86", country: "CN", label: "🇨🇳 China (+86)" },
    { code: "+33", country: "FR", label: "🇫🇷 France (+33)" },
    { code: "+49", country: "DE", label: "🇩🇪 Germany (+49)" },
    { code: "+91", country: "IN", label: "🇮🇳 India (+91)" },
    { code: "+62", country: "ID", label: "🇮🇩 Indonesia (+62)" },
    { code: "+964", country: "IQ", label: "🇮🇶 Iraq (+964)" },
    { code: "+353", country: "IE", label: "🇮🇪 Ireland (+353)" },
    { code: "+972", country: "IL", label: "🇮🇱 Israel (+972)" },
    { code: "+39", country: "IT", label: "🇮🇹 Italy (+39)" },
    { code: "+81", country: "JP", label: "🇯🇵 Japan (+81)" },
    { code: "+965", country: "KW", label: "🇰🇼 Kuwait (+965)" },
    { code: "+60", country: "MY", label: "🇲🇾 Malaysia (+60)" },
    { code: "+960", country: "MV", label: "🇲🇻 Maldives (+960)" },
    { code: "+230", country: "MU", label: "🇲🇺 Mauritius (+230)" },
    { code: "+52", country: "MX", label: "🇲🇽 Mexico (+52)" },
    { code: "+977", country: "NP", label: "🇳🇵 Nepal (+977)" },
    { code: "+31", country: "NL", label: "🇳🇱 Netherlands (+31)" },
    { code: "+64", country: "NZ", label: "🇳🇿 New Zealand (+64)" },
    { code: "+234", country: "NG", label: "🇳🇬 Nigeria (+234)" },
    { code: "+968", country: "OM", label: "🇴🇲 Oman (+968)" },
    { code: "+92", country: "PK", label: "🇵🇰 Pakistan (+92)" },
    { code: "+974", country: "QA", label: "🇶🇦 Qatar (+974)" },
    { code: "+7", country: "RU", label: "🇷🇺 Russia (+7)" },
    { code: "+966", country: "SA", label: "🇸🇦 Saudi Arabia (+966)" },
    { code: "+65", country: "SG", label: "🇸🇬 Singapore (+65)" },
    { code: "+27", country: "ZA", label: "🇿🇦 South Africa (+27)" },
    { code: "+82", country: "KR", label: "🇰🇷 South Korea (+82)" },
    { code: "+34", country: "ES", label: "🇪🇸 Spain (+34)" },
    { code: "+94", country: "LK", label: "🇱🇰 Sri Lanka (+94)" },
    { code: "+255", country: "TZ", label: "🇹🇿 Tanzania (+255)" },
    { code: "+66", country: "TH", label: "🇹🇭 Thailand (+66)" },
    { code: "+90", country: "TR", label: "🇹🇷 Turkey (+90)" },
    { code: "+256", country: "UG", label: "🇺🇬 Uganda (+256)" },
    { code: "+971", country: "AE", label: "🇦🇪 United Arab Emirates (+971)" },
    { code: "+44", country: "GB", label: "🇬🇧 United Kingdom (+44)" },
    { code: "+1", country: "US", label: "🇺🇸 United States (+1)" },
    { code: "+967", country: "YE", label: "🇾🇪 Yemen (+967)" },
    { code: "+263", country: "ZW", label: "🇿🇼 Zimbabwe (+263)" }
    // Add the rest of your list here if needed
  ];
  
  export const SPECIALTIES = [
    "CARDIAC SCIENCES (CARDIOLOGY AND CTVS)",
    "ORTHOPAEDICS",
    "NEURO SCIENCES (NEUROLOGY AND NEUROSURGERY)",
    "GENERAL SURGERY",
    "ENT",
    "GYNAECOLOGY",
    "UROLOGY",
    "GASTROENTEROLOGY",
    "BARIATRIC SURGERIES",
    "INFERTILITY / IVF",
    "OPTHALMOLOGY",
    "PLASTIC AND RECONSTRUCTIVE SURGERIES",
    "PSYCHIATRY",
    "RADIATIONAL ONCOLOGY",
    "SURGICAL ONCOLOGY",
    "PAEDIATRIC SURGERIES",
    "DENTISTRY",
    "ONCOLOGY (MEDICAL, SURGICAL AND RADTIONAL)",
    "GENERAL MEDICINE",
    "INTERVENTIONAL RADIOLOGY",
    "ORAL AND MAXILLOFACIAL SURGERY",
    "PALLIATIVE CARE",
    "GERAITRIC MEDICINE",
    "PHYSICAL MEDICINE AND REHABILITATION",
    "RESPIRATORY AND PULMONOLOGY MEDICINE",
    "OTHERS"
  ];
  